server:
  port: 80

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java/**
      exclude: static/**

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.79.45.67:5432/Java2Project
    username: temp
    password: jkl123456
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/META-INF/resources/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl